CREATE TABLE IF NOT EXISTS fixed_assets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(120) NOT NULL,
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(15, 2) NOT NULL DEFAULT 0,
    depreciation_method VARCHAR(50) NOT NULL DEFAULT 'straight_line',
    useful_life_years INT NOT NULL,
    residual_value DECIMAL(15, 2) NOT NULL DEFAULT 0,
    location VARCHAR(255) DEFAULT NULL,
    supplier VARCHAR(255) DEFAULT NULL,
    status ENUM('active', 'retired', 'disposed') NOT NULL DEFAULT 'active',
    retirement_date DATE DEFAULT NULL,
    disposal_amount DECIMAL(15, 2) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_fixed_assets_company (company_id),
    INDEX idx_fixed_assets_status (status),
    CONSTRAINT fk_fixed_assets_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS client_supplier_registers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type ENUM('client', 'supplier') NOT NULL,
    category ENUM('company', 'individual') NOT NULL,
    tax_id VARCHAR(100) NOT NULL,
    contact_person VARCHAR(255) DEFAULT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    agreement_file_name VARCHAR(255) DEFAULT NULL,
    agreement_file_path VARCHAR(500) DEFAULT NULL,
    status ENUM('Active', 'Inactive') NOT NULL DEFAULT 'Active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_client_supplier_company (company_id),
    INDEX idx_client_supplier_type (type),
    CONSTRAINT fk_client_supplier_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tax_returns (
    id INT AUTO_INCREMENT PRIMARY KEY,
    company_id INT NOT NULL,
    tax_type VARCHAR(20) NOT NULL,
    period VARCHAR(50) NOT NULL,
    submission_date DATE DEFAULT NULL,
    total_declared DECIMAL(15, 2) NOT NULL DEFAULT 0,
    status ENUM('Filed', 'Pending', 'Overdue') NOT NULL DEFAULT 'Pending',
    due_date DATE NOT NULL,
    quarter VARCHAR(10) DEFAULT NULL,
    tax_year VARCHAR(10) DEFAULT NULL,
    payload_json LONGTEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_tax_returns_company (company_id),
    INDEX idx_tax_returns_type (tax_type),
    INDEX idx_tax_returns_due_date (due_date),
    CONSTRAINT fk_tax_returns_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE
);
